In [22]:
import numpy as np
import torch
from pomegranate.distributions import Categorical
from pomegranate.distributions import ConditionalCategorical
from pomegranate.bayesian_network import BayesianNetwork

In [23]:
X = np.random.randint(2, size=(10, 2))
X

array([[0, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [19]:

d1 = Categorical([[0.1, 0.9]])
d2 = ConditionalCategorical([[[0.4, 0.6], [0.3, 0.7]]])

model = BayesianNetwork([d1, d2], [(d1, d2)])

In [20]:
model

BayesianNetwork(
  (distributions): ModuleList(
    (0): Categorical()
    (1): ConditionalCategorical(
      (probs): ParameterList(  (0): Parameter containing: [torch.float32 of size 2x2])
      (_w_sum): [tensor([0., 0.])]
      (_xw_sum): [tensor([[0., 0.],
              [0., 0.]])]
      (_log_probs): [tensor([[-0.9163, -0.5108],
              [-1.2040, -0.3567]])]
    )
  )
  (_factor_graph): FactorGraph(
    (factors): ModuleList(
      (0): Categorical()
      (1): JointCategorical()
    )
    (marginals): ModuleList(
      (0-1): 2 x Categorical()
    )
  )
)

In [27]:
X_torch = torch.tensor(X[:4])
X_torch

tensor([[0, 0],
        [1, 1],
        [0, 1],
        [1, 0]])

In [26]:

mask = torch.tensor([[True, False],
                     [False, True],
                     [True, True],
                     [False, False]])

X_masked = torch.masked.MaskedTensor(X_torch, mask=mask)
model.predict_proba(X_masked)

[tensor([[1.0000, 0.0000],
         [0.0870, 0.9130],
         [1.0000, 0.0000],
         [0.1000, 0.9000]]),
 tensor([[0.4000, 0.6000],
         [0.0000, 1.0000],
         [0.0000, 1.0000],
         [0.3100, 0.6900]])]

In [6]:
X = torch.randint(2, size=(20, 4))

d1 = Categorical([[0.1, 0.9]])
d2 = Categorical([[0.3, 0.7]])
d3 = ConditionalCategorical([[[0.4, 0.6], [0.3, 0.7]]])
d4 = ConditionalCategorical([[[[0.8, 0.2], [0.1, 0.9]], [[0.1, 0.9], [0.5, 0.5]]]])

model = BayesianNetwork([d1, d2, d3, d4], [(d1, d3), (d2, d4), (d3, d4)])
model.summarize(X[:5])
model.summarize(X[5:])
model.from_summaries()

In [8]:
model.distributions[0].probs

Parameter containing:
tensor([[0.5000, 0.5000]])

In [15]:
model.distributions[2].probs[0]

Parameter containing:
tensor([[0.4000, 0.6000],
        [0.7000, 0.3000]])