In [2]:
import numpy as np
import torch
from pomegranate.distributions import Categorical
from pomegranate.distributions import ConditionalCategorical
from pomegranate.bayesian_network import BayesianNetwork

In [11]:
X = np.random.randint(2, size=(10, 2))
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1]])

In [50]:
torch.tensor([0.1, 0.8, 0.1]).softmax(dim=-1)

[0.24914337694644928, 0.5017131567001343, 0.24914337694644928]

In [43]:
Categorical([[0.1, 0.8, 0.1]])

Categorical()

In [35]:

d1 = Categorical([[0.1, 0.8, 0.1]])
d2 = ConditionalCategorical([[[0.4, 0.6], [0.3, 0.7], [0.3, 0.7]]])

model = BayesianNetwork([d1, d2], [(d1, d2)])

In [51]:

d4 = ConditionalCategorical([[[[0.8, 0.2], [0.1, 0.9]], [[0.1, 0.9], [0.5, 0.5]]]])
d4

ConditionalCategorical(
  (probs): ParameterList(  (0): Parameter containing: [torch.float32 of size 2x2x2])
  (_w_sum): [tensor([[0., 0.],
          [0., 0.]])]
  (_xw_sum): [tensor([[[0., 0.],
           [0., 0.]],
  
          [[0., 0.],
           [0., 0.]]])]
  (_log_probs): [tensor([[[-0.2231, -1.6094],
           [-2.3026, -0.1054]],
  
          [[-2.3026, -0.1054],
           [-0.6931, -0.6931]]])]
)

In [52]:

def get_rng(seed):
	return torch.Generator().manual_seed(seed)
get_rng(8099045677)

In [65]:
d1.probs.shape[-1]

3

In [36]:
model

BayesianNetwork(
  (distributions): ModuleList(
    (0): Categorical()
    (1): ConditionalCategorical(
      (probs): ParameterList(  (0): Parameter containing: [torch.float32 of size 3x2])
      (_w_sum): [tensor([0., 0., 0.])]
      (_xw_sum): [tensor([[0., 0.],
              [0., 0.],
              [0., 0.]])]
      (_log_probs): [tensor([[-0.9163, -0.5108],
              [-1.2040, -0.3567],
              [-1.2040, -0.3567]])]
    )
  )
  (_factor_graph): FactorGraph(
    (factors): ModuleList(
      (0): Categorical()
      (1): JointCategorical()
    )
    (marginals): ModuleList(
      (0-1): 2 x Categorical()
    )
  )
)

In [37]:
X_torch = torch.tensor(X[:4]).long()
X_torch[:] = 1
X_torch

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

In [38]:
X_torch = torch.tensor([[1, 1],
        [1, 0],
        # [0, 1],
        [1, 1],
        [1, 1]])

mask = torch.tensor([[True, False],
                     [True, False],
                     [True, True],
                     [False, False]])

X_masked = torch.masked.MaskedTensor(X_torch, mask=mask)
model.predict_proba(X_masked)

[tensor([[0.0000, 1.0000, 0.0000],
         [0.0000, 1.0000, 0.0000],
         [0.0000, 1.0000, 0.0000],
         [0.1000, 0.8000, 0.1000]]),
 tensor([[0.3000, 0.7000],
         [0.3000, 0.7000],
         [0.0000, 1.0000],
         [0.3100, 0.6900]])]

In [8]:
X = torch.randint(2, size=(20, 4))

d1 = Categorical([[0.1, 0.9]])
d2 = Categorical([[0.3, 0.7]])
d3 = ConditionalCategorical([[[0.4, 0.6], [0.3, 0.7]]])
d4 = ConditionalCategorical([[[[0.8, 0.2], [0.1, 0.9]], [[0.1, 0.9], [0.5, 0.5]]]])

model = BayesianNetwork([d1, d2, d3, d4], [(d1, d3), (d2, d4), (d3, d4)])
model.summarize(X[:5])
model.summarize(X[5:])
model.from_summaries()

In [9]:
model.distributions[0].probs

Parameter containing:
tensor([[0.4000, 0.6000]])

In [10]:
model.distributions[2].probs[0]

Parameter containing:
tensor([[0.6250, 0.3750],
        [0.5000, 0.5000]])